name: Strapi Cloud Build CI
on:
  pull_request:

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  SERVICE_NAME: helloworld-nodejs

jobs:

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"