name: Strapi Cloud Build CI
on:
  pull_request:

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  SERVICE_NAME: helloworld-nodejs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

    # Build and push image to Google Container Registry
      - name: Build docker image
        run: docker build -t gcr.io/portfolio-337413/strapi-staging .